import type { MarketCandidate, MarketDataProvider } from "@/lib/opportunity-types";

const mockUniverseCount = 42;

const mockCandidates: MarketCandidate[] = [
  {
    ticker: "NVDA",
    companyName: "NVIDIA Corp.",
    trend: "Bullish",
    riskLevel: "Medium",
    potentialRewardPct: 7.4,
    setupType: "Pullback",
    aboveMovingAverages: true,
    volumeTrend: "Increasing",
  supportHeld: true,
  momentumScore: 86,
  priceExtended: true,
  earningsSoon: false,
  sector: "Technology",
  },
  {
    ticker: "MSFT",
    companyName: "Microsoft Corp.",
    trend: "Bullish",
    riskLevel: "Low",
    potentialRewardPct: 4.8,
    setupType: "Trend Continuation",
    aboveMovingAverages: true,
    volumeTrend: "Stable",
    supportHeld: true,
    momentumScore: 78,
    priceExtended: false,
    earningsSoon: false,
    sector: "Technology",
  },
  {
    ticker: "AMD",
    companyName: "Advanced Micro Devices",
    trend: "Neutral",
    riskLevel: "Medium",
    potentialRewardPct: 6.2,
    setupType: "Breakout",
    aboveMovingAverages: true,
    volumeTrend: "Increasing",
    supportHeld: false,
    momentumScore: 70,
    priceExtended: false,
    earningsSoon: true,
    sector: "Technology",
  },
  {
    ticker: "JPM",
    companyName: "JPMorgan Chase & Co.",
    trend: "Neutral",
    riskLevel: "Low",
    potentialRewardPct: 3.9,
    setupType: "Support Bounce",
    aboveMovingAverages: false,
    volumeTrend: "Stable",
    supportHeld: true,
    momentumScore: 62,
    priceExtended: false,
    earningsSoon: false,
    sector: "Financials",
  },
  {
    ticker: "TSLA",
    companyName: "Tesla Inc.",
    trend: "Bearish",
    riskLevel: "High",
    potentialRewardPct: 9.1,
    setupType: "Range Reversal",
    aboveMovingAverages: false,
    volumeTrend: "Fading",
    supportHeld: true,
    momentumScore: 58,
    priceExtended: false,
    earningsSoon: true,
    sector: "Consumer",
  },
];

export const mockMarketDataProvider: MarketDataProvider = {
  getUniverseCount: () => mockUniverseCount,
  getCandidates: () => mockCandidates,
  getPipelineStats: () => ({
    stocksAnalyzed: 503,
    passedTechnicalFilters: 42,
    showedInstitutionalStrength: 11,
    matchedTodayMarket: 5,
    matchedTraderDna: 2,
  }),
  getMarketMood: () => ({
    todayMarket: "Bullish",
    marketBreadth: "Mixed",
    volatility: "Medium",
    sectorLeadership: "Technology",
    interpretation:
      "The market is constructive, but patience is still required. Strong opportunities should confirm before entry.",
  }),
};
